# Generated by Django 4.2 on 2024-04-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='1994-02-23'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='introduction',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
